FROM python:3.9-slim

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      sudo \
      qemu-system-x86 \
      qemu-kvm \
      net-tools \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY scripts/pdaemon.sh /app/scripts/pdaemon.sh
COPY xqueue_watcher /app/xqueue_watcher
COPY tasks /app/tasks

RUN pip install --no-cache-dir requests
RUN mkdir status
RUN touch status/task
RUN touch status/state
RUN chmod +x /app/scripts/pdaemon.sh /app/tasks/checker.py

ENTRYPOINT ["bash", "/app/scripts/pdaemon.sh"]
