FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        sudo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY scripts/pdaemon.sh /app/scripts/pdaemon.sh
COPY xqueue_watcher /app/xqueue_watcher

RUN pip install --no-cache-dir requests
RUN chmod +x /app/scripts/pdaemon.sh

ENTRYPOINT ["bash", "/app/scripts/pdaemon.sh"]

